In [1]:
!pip install causal-learn


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from causallearn.search.ScoreBased.GES import ges
from causallearn.utils.GraphUtils import GraphUtils
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import io
import numpy as np
import SCM_data
import synthetic_dataset

In [3]:
times = 100
for i in range(1, 6):
    true_count = [0] * 6
    for j in range(times):

        X, Y, Z, G_true, CPDAG = SCM_data.generate_scm_data(i, n_samples=10000)

        data = np.array([X, Y, Z]).T
        Record = ges(data)
        # equals
        if np.array_equal(CPDAG, Record['G'].graph): true_count[i-1] += 1
    print(f"SCM {i} : {true_count[i-1]/times}")

SCM 1 : 1.0
SCM 2 : 1.0
SCM 3 : 1.0
SCM 4 : 1.0
SCM 5 : 1.0


In [10]:
G_true = np.array([[0,1,0],[0,0,0],[0,1,0]])
X = synthetic_dataset.dataset_based_on_B(G_true,1000,1,'gaussian_ev')
Record = ges(X)
print(Record["G"].graph)
print(G_true)

[[ 0 -1  0]
 [ 1  0  1]
 [ 0 -1  0]]
[[0 1 0]
 [0 0 0]
 [0 1 0]]
