In [2]:
from causallearn.search.PermutationBased.GRaSP import grasp
import numpy as np
import SCM_data

In [16]:
times = 100
for i in range(1, 6):
    true_count = [0] * 6
    for j in range(times):
        X, Y, Z, G_true, CPDAG = SCM_data.generate_scm_data(i, n_samples=10000)

        data = np.array([X, Y, Z]).T
        G_est = grasp(data, verbose=False).graph
        # equals
        if np.array_equal(CPDAG, G_est): true_count[i-1] += 1
        else:
            print(CPDAG)
            print(G_est)
    print(f"SCM {i} : {true_count[i-1]/times}")

SCM 1 : 1.0
SCM 2 : 1.0
[[ 0 -1  0]
 [ 1  0  1]
 [ 0 -1  0]]
[[ 0 -1 -1]
 [-1  0 -1]
 [-1 -1  0]]
SCM 3 : 0.99
SCM 4 : 1.0
SCM 5 : 1.0
