In [10]:
import sys, os
import numpy as np
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
sys.path.append(r"c:\Users\super\DAG\golemMain\src")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
from MEC import is_in_markov_equiv_class
print(os.getcwd())
from SCM_data import generate_scm_from_BN 
from numpy.linalg import inv
from scipy.linalg import sqrtm

from coordinate_descent.tune_cd0_cv import tune_dag_l0_cv

c:\Users\super\DAG


In [11]:
# n = 10000
# d=5, e=4, |v|=1
print("d=5, e=4, |v|=1")

B_true = np.array([
    [0, 0, 1, 2, 0],
    [0, 0, 0, 2, 3],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])
N = [1, 2, 3, 2, 1]

data, G, B, Sigma = generate_scm_from_BN(B_true.T, n_samples=10000, N=N, seed=42)
R_hat = np.cov(data.T)
print("R_hat= \n",np.array2string(R_hat, formatter={'float_kind':lambda x: f"{x:.2f}"}))
d = R_hat.shape[0]

Omega_true = [[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0],[0,0,0,2,0],[0,0,0,0,1]]
print(inv(sqrtm(Omega_true)))
Theta_hat = inv(R_hat)
A_true = (np.eye(d) - B_true) @ inv(sqrtm(Omega_true))
print("A_true= \n",np.array2string(A_true, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print(np.trace(A_true.T @ R_hat @ A_true))
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)
print("likelihood_true = ", likelihood_true)


best_params, best_score, study = tune_dag_l0_cv(data, T = 5000)

print("\n===== Tuning Result =====")
print("Best CV NLL:", best_score)
print("Best parameters:")
for k, v in best_params.items():
    print(f"  {k}: {v}")


[I 2025-12-20 18:49:35,000] A new study created in memory with name: no-name-c628c6ec-e112-40f4-9a1a-de351402c2d7


d=5, e=4, |v|=1
R_hat= 
 [[1.00 0.03 0.97 2.07 0.10]
 [0.03 2.00 0.02 4.07 5.99]
 [0.97 0.02 3.88 1.96 0.09]
 [2.07 4.07 1.96 14.38 12.19]
 [0.10 5.99 0.09 12.19 18.92]]
[[1.         0.         0.         0.         0.        ]
 [0.         0.70710677 0.         0.         0.        ]
 [0.         0.         0.57735026 0.         0.        ]
 [0.         0.         0.         0.70710677 0.        ]
 [0.         0.         0.         0.         1.        ]]
A_true= 
 [[1.00 0.00 -0.58 -1.41 0.00]
 [0.00 0.71 0.00 -1.41 -3.00]
 [0.00 0.00 0.58 0.00 0.00]
 [0.00 0.00 0.00 0.71 0.00]
 [0.00 0.00 0.00 0.00 1.00]]
5.026304608930029
likelihood_true =  7.511211363071577


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-12-20 18:51:03,397] Trial 0 finished with value: 7.5727620131753755 and parameters: {'lambda_l0': 0.12520653814999466, 'threshold': 0.14588597961075972}. Best is trial 0 with value: 7.5727620131753755.
[I 2025-12-20 18:52:31,728] Trial 1 finished with value: 7.552945716028029 and parameters: {'lambda_l0': 0.16051911333587626, 'threshold': 0.1135278047694104}. Best is trial 1 with value: 7.552945716028029.
[I 2025-12-20 18:54:10,211] Trial 2 finished with value: 7.572951294433617 and parameters: {'lambda_l0': 0.07035737028722146, 'threshold': 0.13271988148266467}. Best is trial 1 with value: 7.552945716028029.
[I 2025-12-20 18:56:10,935] Trial 3 finished with value: 7.572956950258947 and parameters: {'lambda_l0': 0.07501954443620121, 'threshold': 0.17943687014859516}. Best is trial 1 with value: 7.552945716028029.
[I 2025-12-20 18:57:57,105] Trial 4 finished with value: 8.323387414976217 and parameters: {'lambda_l0': 0.8459126528049372, 'threshold': 0.08285388857689777}. Best is

In [12]:
# n = 1000
# d=5, e=4, |v|=1
print("d=5, e=4, |v|=1")

B_true = np.array([
    [0, 0, 1, 2, 0],
    [0, 0, 0, 2, 3],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])
N = [1, 2, 3, 2, 1]

data, G, B, Sigma = generate_scm_from_BN(B_true.T, n_samples=1000, N=N, seed=42)
R_hat = np.cov(data.T)
print("R_hat= \n",np.array2string(R_hat, formatter={'float_kind':lambda x: f"{x:.2f}"}))
d = R_hat.shape[0]

Omega_true = [[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0],[0,0,0,2,0],[0,0,0,0,1]]
print(inv(sqrtm(Omega_true)))
Theta_hat = inv(R_hat)
A_true = (np.eye(d) - B_true) @ inv(sqrtm(Omega_true))
print("A_true= \n",np.array2string(A_true, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print(np.trace(A_true.T @ R_hat @ A_true))
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)
print("likelihood_true = ", likelihood_true)


best_params, best_score, study = tune_dag_l0_cv(data, T = 5000)

print("\n===== Tuning Result =====")
print("Best CV NLL:", best_score)
print("Best parameters:")
for k, v in best_params.items():
    print(f"  {k}: {v}")


d=5, e=4, |v|=1


[I 2025-12-20 20:08:09,608] A new study created in memory with name: no-name-b3e7f4ca-a7d1-4c2e-a433-b5c01d34a457


R_hat= 
 [[1.00 0.07 0.90 2.19 0.24]
 [0.07 2.15 0.09 4.40 6.46]
 [0.90 0.09 3.60 2.02 0.31]
 [2.19 4.40 2.02 15.26 13.33]
 [0.24 6.46 0.31 13.33 20.37]]
[[1.         0.         0.         0.         0.        ]
 [0.         0.70710677 0.         0.         0.        ]
 [0.         0.         0.57735026 0.         0.        ]
 [0.         0.         0.         0.70710677 0.        ]
 [0.         0.         0.         0.         1.        ]]
A_true= 
 [[1.00 0.00 -0.58 -1.41 0.00]
 [0.00 0.71 0.00 -1.41 -3.00]
 [0.00 0.00 0.58 0.00 0.00]
 [0.00 0.00 0.00 0.71 0.00]
 [0.00 0.00 0.00 0.00 1.00]]
4.9960143676988675
likelihood_true =  7.4809211218404155


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-12-20 20:09:35,010] Trial 0 finished with value: 7.532778480297111 and parameters: {'lambda_l0': 0.12520653814999466, 'threshold': 0.14588597961075972}. Best is trial 0 with value: 7.532778480297111.
[I 2025-12-20 20:11:12,244] Trial 1 finished with value: 7.53882076047199 and parameters: {'lambda_l0': 0.16051911333587626, 'threshold': 0.1135278047694104}. Best is trial 0 with value: 7.532778480297111.
[I 2025-12-20 20:12:44,698] Trial 2 finished with value: 7.543965003578991 and parameters: {'lambda_l0': 0.07035737028722146, 'threshold': 0.13271988148266467}. Best is trial 0 with value: 7.532778480297111.
[I 2025-12-20 20:14:13,685] Trial 3 finished with value: 7.544329758373226 and parameters: {'lambda_l0': 0.07501954443620121, 'threshold': 0.17943687014859516}. Best is trial 0 with value: 7.532778480297111.
[I 2025-12-20 20:15:46,614] Trial 4 finished with value: 8.277401166837567 and parameters: {'lambda_l0': 0.8459126528049372, 'threshold': 0.08285388857689777}. Best is tr

In [13]:
# d=5, e=4, |v|=1
# n = 200
print("d=5, e=4, |v|=1")

B_true = np.array([
    [0, 0, 1, 2, 0],
    [0, 0, 0, 2, 3],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])
N = [1, 2, 3, 2, 1]

data, G, B, Sigma = generate_scm_from_BN(B_true.T, n_samples=200, N=N, seed=42)
R_hat = np.cov(data.T)
print("R_hat= \n",np.array2string(R_hat, formatter={'float_kind':lambda x: f"{x:.2f}"}))
d = R_hat.shape[0]

Omega_true = [[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0],[0,0,0,2,0],[0,0,0,0,1]]
print(inv(sqrtm(Omega_true)))
Theta_hat = inv(R_hat)
A_true = (np.eye(d) - B_true) @ inv(sqrtm(Omega_true))
print("A_true= \n",np.array2string(A_true, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print(np.trace(A_true.T @ R_hat @ A_true))
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)
print("likelihood_true = ", likelihood_true)


best_params, best_score, study = tune_dag_l0_cv(data, T = 5000)

print("\n===== Tuning Result =====")
print("Best CV NLL:", best_score)
print("Best parameters:")
for k, v in best_params.items():
    print(f"  {k}: {v}")


[I 2025-12-21 17:45:11,000] A new study created in memory with name: no-name-1f2cefdb-e997-4744-8bc9-14699a2501aa


d=5, e=4, |v|=1
R_hat= 
 [[0.95 0.15 0.83 2.17 0.35]
 [0.15 1.75 0.23 3.71 5.39]
 [0.83 0.23 3.48 2.26 0.71]
 [2.17 3.71 2.26 13.63 11.33]
 [0.35 5.39 0.71 11.33 17.61]]
[[1.         0.         0.         0.         0.        ]
 [0.         0.70710677 0.         0.         0.        ]
 [0.         0.         0.57735026 0.         0.        ]
 [0.         0.         0.         0.70710677 0.        ]
 [0.         0.         0.         0.         1.        ]]
A_true= 
 [[1.00 0.00 -0.58 -1.41 0.00]
 [0.00 0.71 0.00 -1.41 -3.00]
 [0.00 0.00 0.58 0.00 0.00]
 [0.00 0.00 0.00 0.71 0.00]
 [0.00 0.00 0.00 0.00 1.00]]
4.882804937819453
likelihood_true =  7.367711691961001


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-12-21 17:46:53,225] Trial 0 finished with value: 7.48032266595082 and parameters: {'lambda_l0': 0.12520653814999466, 'threshold': 0.14588597961075972}. Best is trial 0 with value: 7.48032266595082.
[I 2025-12-21 17:48:36,584] Trial 1 finished with value: 7.455627809201118 and parameters: {'lambda_l0': 0.16051911333587626, 'threshold': 0.1135278047694104}. Best is trial 1 with value: 7.455627809201118.
[I 2025-12-21 17:50:17,533] Trial 2 finished with value: 7.480844633788491 and parameters: {'lambda_l0': 0.07035737028722146, 'threshold': 0.13271988148266467}. Best is trial 1 with value: 7.455627809201118.
[I 2025-12-21 17:52:00,239] Trial 3 finished with value: 7.485739649194818 and parameters: {'lambda_l0': 0.07501954443620121, 'threshold': 0.17943687014859516}. Best is trial 1 with value: 7.455627809201118.
[I 2025-12-21 17:53:42,276] Trial 4 finished with value: 8.144936798711377 and parameters: {'lambda_l0': 0.8459126528049372, 'threshold': 0.08285388857689777}. Best is tri

1.N=10000
Best CV NLL: 7.512067086466199
Best parameters:
  lambda_l0: 0.012835991938860869
  threshold: 0.13344079127624334

2.N=1000
Best CV NLL: 7.494203175766098
Best parameters:
  lambda_l0: 0.012400785212072286
  threshold: 0.033047851245886634

3.N=200
Best CV NLL: 7.453255604468761
Best parameters:
  lambda_l0: 0.17659742441655982
  threshold: 0.10122404559911613

Test These parameters:

In [14]:
import sys, os
import numpy as np
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
sys.path.append(r"c:\Users\super\DAG\golemMain\src")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
from MEC import is_in_markov_equiv_class
print(os.getcwd())
from SCM_data import generate_scm_from_BN 
from numpy.linalg import inv
from scipy.linalg import sqrtm
from nodag.nodag_gumbel_softmax import train_gumbel_sgd_dag
from nodag.nodag_gs_findbest import nodag_fb_l_dag
from golemMain.src.golem import golem
from coordinate_descent.coordinate import dag_coordinate_descent, weight_to_adjacency
from coordinate_descent.coordinate0 import dag_coordinate_descent_l0

c:\Users\super\DAG


In [15]:
experiments = []

# ----------- Experiment 1 -----------
experiments.append({
    "name": "d=3, A→B←C",
    "B_true": np.array([
        [0, 1, 0],
        [0, 0, 0],
        [0, 2, 0]
    ]),
    "N": np.array([1, 2, 3]),
    "Omega_true": np.diag([1, 2, 3])
})

# ----------- Experiment 2 -----------
experiments.append({
    "name": "d=3, A→B→C",
    "B_true": np.array([
        [0, 1, 0],
        [0, 0, 3],
        [0, 0, 0]
    ]),
    "N": np.array([1, 3, 4]),
    "Omega_true": np.diag([1, 3, 4])
})

# ----------- Experiment 3 -----------
experiments.append({
    "name": "d=3, A→B→C + A→C",
    "B_true": np.array([
        [0, 1, 2],
        [0, 0, 3],
        [0, 0, 0]
    ]),
    "N": np.array([5, 4, 3]),
    "Omega_true": np.diag([5, 4, 3])
})

# ----------- Experiment 4 -----------
experiments.append({
    "name": "d=4, A→B, B→C, B→D",
    "B_true": np.array([
        [0, 2, 0, 0],
        [0, 0, 3, 4],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ]),
    "N": np.array([1, 4, 3, 2]),
    "Omega_true": np.diag([1, 4, 3, 2])
})

# ----------- Experiment 5 -----------
experiments.append({
    "name": "d=4, A→C, A→D, B→C, B→D",
    "B_true": np.array([
        [0, 0, 2, 3],
        [0, 0, 3, 4],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ]),
    "N": np.array([2, 4, 3, 5]),
    "Omega_true": np.diag([2, 4, 3, 5])
})

# ----------- Experiment 6 -----------
experiments.append({
    "name": "d=4, A→D, B→D, C→D",
    "B_true": np.array([
        [0, 0, 0, 1],
        [0, 0, 0, 3],
        [0, 0, 0, 5],
        [0, 0, 0, 0]
    ]),
    "N": np.array([5, 4, 3, 2]),
    "Omega_true": np.diag([5, 4, 3, 2])
})

# ----------- Experiment 7 -----------
experiments.append({
    "name": "d=5, e=4, |v|=0",
    "B_true": np.array([
        [0, 1, 0, 2, 0],
        [0, 0, 3, 0, 4],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]),
    "N": np.array([1, 2, 3, 2, 1]),
    "Omega_true": np.diag([1, 2, 3, 2, 1])
})

# ----------- Experiment 8 -----------
experiments.append({
    "name": "d=5, e=4, |v|=1",
    "B_true": np.array([
        [0, 0, 1, 2, 0],
        [0, 0, 0, 2, 3],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]),
    "N": np.array([1, 2, 3, 2, 1]),
    "Omega_true": np.diag([1, 2, 3, 2, 1])
})

# ----------- Experiment 9 -----------
experiments.append({
    "name": "d=5, e=4, |v|=2",
    "B_true": np.array([
        [0, 0, 0, 1, 0],
        [0, 0, 0, 2, 3],
        [0, 0, 0, 0, 4],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]),
    "N": np.array([1, 2, 3, 2, 1]),
    "Omega_true": np.diag([1, 2, 3, 2, 1])
})


In [16]:
def run_one_coordinate0(B_true, N, name=None,
                       n_samples=10000,
                       threshold=0.05,
                       T=300,
                       lambda_l0=0.2,
                       n_repeats=100):
    if name is None:
        name = "Unnamed experiment"
    print("=" * 80)
    print(f"Running: {name}")

    G_true = weight_to_adjacency(B_true, threshold)
    N = np.array(N)

    data, G, B, Sigma = generate_scm_from_BN(
        B_true.T, n_samples=n_samples, N=N, seed=42
    )
    R_hat = np.cov(data.T)
    print("R_hat =\n", np.array2string(
        R_hat, formatter={'float_kind': lambda x: f"{x:.2f}"}
    ))

    d = R_hat.shape[0]

    Omega_true = np.diag(N)
    print("inv(sqrtm(Omega_true)) =\n", inv(sqrtm(Omega_true)))

    Theta_hat = inv(R_hat)
    A_true = (np.eye(d) - B_true) @ inv(sqrtm(Omega_true))
    print("A_true =\n", np.array2string(
        A_true, formatter={'float_kind': lambda x: f"{x:.2f}"}
    ))

    likelihood_true = -2 * np.log(np.linalg.det(A_true)) \
                      + np.trace(A_true.T @ R_hat @ A_true)
    print("likelihood_true =", likelihood_true)

    correct = 0
    for seed in range(n_repeats):
        A_opt, G_opt, fval = dag_coordinate_descent_l0(
            R_hat,
            T=T,
            seed=seed,
            threshold=threshold,
            lambda_l0=lambda_l0
        )
        if is_in_markov_equiv_class(G_true, G_opt):
            correct += 1

    print("Correct rate =", correct / n_repeats)


In [20]:
# 1.N=10000
# Best CV NLL: 7.514632981344995
# Best parameters:
#   lambda_l0: 0.013869861245357327
#   threshold: 0.026554566943292737


for exp in experiments:
    run_one_coordinate0(
        B_true=exp["B_true"],
        N=exp["N"],
        name=exp["name"],
        n_samples=10000,
        threshold=0.13344079127624334,
        lambda_l0=0.012835991938860869,
        T=5000,
        n_repeats=100
    )

Running: d=3, A→B←C
R_hat =
 [[1.02 1.06 0.02]
 [1.06 15.32 6.09]
 [0.02 6.09 3.02]]
inv(sqrtm(Omega_true)) =
 [[1.         0.         0.        ]
 [0.         0.70710677 0.        ]
 [0.         0.         0.57735026]]
A_true =
 [[1.00 -0.71 0.00]
 [0.00 0.71 0.00]
 [0.00 -1.41 0.58]]
likelihood_true = 4.816664771649337
Correct rate = 0.77
Running: d=3, A→B→C
R_hat =
 [[1.02 1.03 3.11]
 [1.03 4.04 12.20]
 [3.11 12.20 40.81]]
inv(sqrtm(Omega_true)) =
 [[1.         0.         0.        ]
 [0.         0.57735026 0.        ]
 [0.         0.         0.5       ]]
A_true =
 [[1.00 -0.58 0.00]
 [0.00 0.58 -1.50]
 [0.00 0.00 0.50]]
likelihood_true = 5.509811952486
Correct rate = 0.64
Running: d=3, A→B→C + A→C
R_hat =
 [[5.08 5.12 25.56]
 [5.12 9.15 37.77]
 [25.56 37.77 167.78]]
inv(sqrtm(Omega_true)) =
 [[0.4472136  0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.57735026]]
A_true =
 [[0.45 -0.50 -1.15]
 [0.00 0.50 -1.73]
 [0.00 0.00 0.58]]
likelihood_true 

In [21]:
# 2.N=1000
# Best CV NLL: 7.49742186247469
# Best parameters:
#   lambda_l0: 0.011650210757807864
#   threshold: 0.07567005890471545


for exp in experiments:
    run_one_coordinate0(
        B_true=exp["B_true"],
        N=exp["N"],
        name=exp["name"],
        n_samples=1000,
        threshold=0.033047851245886634,
        lambda_l0=0.012400785212072286,
        T=5000,
        n_repeats=100
    )

Running: d=3, A→B←C
R_hat =
 [[1.03 0.93 -0.05]
 [0.93 15.72 6.24]
 [-0.05 6.24 3.07]]
inv(sqrtm(Omega_true)) =
 [[1.         0.         0.        ]
 [0.         0.70710677 0.        ]
 [0.         0.         0.57735026]]
A_true =
 [[1.00 -0.71 0.00]
 [0.00 0.71 0.00]
 [0.00 -1.41 0.58]]
likelihood_true = 4.839457313189493
Correct rate = 0.78
Running: d=3, A→B→C
R_hat =
 [[1.03 1.03 3.04]
 [1.03 4.03 12.25]
 [3.04 12.25 41.32]]
inv(sqrtm(Omega_true)) =
 [[1.         0.         0.        ]
 [0.         0.57735026 0.        ]
 [0.         0.         0.5       ]]
A_true =
 [[1.00 -0.58 0.00]
 [0.00 0.58 -1.50]
 [0.00 0.00 0.50]]
likelihood_true = 5.532604494569587
Correct rate = 0.71
Running: d=3, A→B→C + A→C
R_hat =
 [[5.14 5.16 25.63]
 [5.16 9.16 37.89]
 [25.63 37.89 168.07]]
inv(sqrtm(Omega_true)) =
 [[0.4472136  0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.57735026]]
A_true =
 [[0.45 -0.50 -1.15]
 [0.00 0.50 -1.73]
 [0.00 0.00 0.58]]
likelihood_

In [22]:
# 3.N=200
# Best CV NLL: 7.455121907744188
# Best parameters:
#   lambda_l0: 0.16051911333587626
#   threshold: 0.1135278047694104


for exp in experiments:
    run_one_coordinate0(
        B_true=exp["B_true"],
        N=exp["N"],
        name=exp["name"],
        n_samples=200,
        threshold=0.10122404559911613,
        lambda_l0=0.17659742441655982,
        T=5000,
        n_repeats=100
    )

Running: d=3, A→B←C
R_hat =
 [[1.02 0.83 -0.13]
 [0.83 13.78 5.33]
 [-0.13 5.33 2.65]]
inv(sqrtm(Omega_true)) =
 [[1.         0.         0.        ]
 [0.         0.70710677 0.        ]
 [0.         0.         0.57735026]]
A_true =
 [[1.00 -0.71 0.00]
 [0.00 0.71 0.00]
 [0.00 -1.41 0.58]]
likelihood_true = 4.642520273764008
Correct rate = 0.78
Running: d=3, A→B→C
R_hat =
 [[1.02 1.11 3.17]
 [1.11 4.04 12.18]
 [3.17 12.18 40.31]]
inv(sqrtm(Omega_true)) =
 [[1.         0.         0.        ]
 [0.         0.57735026 0.        ]
 [0.         0.         0.5       ]]
A_true =
 [[1.00 -0.58 0.00]
 [0.00 0.58 -1.50]
 [0.00 0.00 0.50]]
likelihood_true = 5.335667450262973
Correct rate = 0.65
Running: d=3, A→B→C + A→C
R_hat =
 [[5.10 5.33 25.89]
 [5.33 9.34 38.62]
 [25.89 38.62 169.51]]
inv(sqrtm(Omega_true)) =
 [[0.4472136  0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.57735026]]
A_true =
 [[0.45 -0.50 -1.15]
 [0.00 0.50 -1.73]
 [0.00 0.00 0.58]]
likelihood_