In [1]:
import sys, os
import numpy as np
from numpy.linalg import LinAlgError, inv
from scipy.linalg import sqrtm

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
print(os.getcwd())

c:\Users\super\DAG\nodag


In [2]:
from nodag.nodag_gs_findbest import nodag_findbest_loss, nodag_findbest_likelihood_penalty, calculate_shd

In [4]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.01

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.01, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[ 1.01300613e+00  7.26071777e-03 -2.43083802e-03 -4.66034656e-02]
 [-5.56995690e+00  1.00727054e+00 -7.38569651e-03 -1.37338231e-02]
 [ 3.25044185e-01 -9.74064382e-01  1.00264926e+00  3.03785023e-01]
 [-1.73771557e-03 -1.54593101e-02 -5.43124357e-03  9.91349916e-01]]
U = 
 [[ 8.19852192e+04 -1.19647741e+00 -1.52506522e+00 -6.40326952e+00]
 [-1.22135935e+01  1.89296151e+02  1.38155096e+01 -1.78347279e+00]
 [-4.47820577e+08 -1.07778325e+03  1.63601989e+04 -5.57609889e+02]
 [ 6.06100002e+10 -1.67567483e+00  1.38155096e+01  9.61482320e+01]]
Final Loss =  4.001982481771426
Final penalty =  0.030033679002612855
Final likelihood =  3.9719488027688135
seed =  223

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.1

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.1, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-1.76780145e-03  7.25260290e-03 -2.38724830e-03  1.01300489e+00]
 [-1.76355659e-02  1.00721943e+00 -7.47334646e-03  7.21129703e-03]
 [-5.62221590e-03 -7.44073488e-03  1.00260784e+00 -1.98278306e+00]
 [ 9.91304077e-01  1.05041256e-01 -5.55965983e-03 -8.78352890e-01]]
U = 
 [[ 9.04415580e-01 -3.57339107e+00 -3.25944050e+00  6.78904578e+02]
 [-3.77195325e+00  2.09646132e+05 -4.58412353e+00 -3.54185890e+00]
 [-3.52532859e+00 -4.00846926e+00  1.38155096e+01 -1.99638267e+03]
 [ 1.38155096e+01 -3.71053062e+01 -3.74973009e+00 -1.30353674e+05]]
Final Loss =  4.172038354721993
Final penalty =  0.2000000159227008
Final likelihood =  3.9720383387992917
seed =  202

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 1

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 1, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 10

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 10, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)