In [1]:
import sys, os
import numpy as np
from numpy.linalg import LinAlgError, inv
from scipy.linalg import sqrtm

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
print(os.getcwd())

from nodag.nodag_gumbel_softmax import train_gumbel_sgd
from nodag.nodag_gs_findbest import nodag_findbest_loss, nodag_findbest_loss_reg, nodag_findbest_loss_reg_reset, nodag_findbest_clamp
from nodag.nodag_gs_findbest import nodag_fb_l_clamp, nodag_fb_l_reg, nodag_fb_l_reg_reset, nodag_findbest_likelihood_penalty


c:\Users\super\DAG\nodag


## Test Regularization on ONE Graph Without Findbest

In [3]:
# No regularization

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

seed = 7
n, d = 10000, 4
graph_type, degree = 'ER', 1    # ER1 graph
B_scale = 1.0
noise_type = 'gaussian_ev'
print("random seed = ", seed)

Dataset = SyntheticDataset(n, d, graph_type, degree,
                        noise_type, B_scale, seed=seed)
data = Dataset.X
B_true = Dataset.B
G_true = Dataset.B_bin

R_hat = np.cov(data.T)
d = R_hat.shape[0]
Omega_true = np.eye(d)
Theta_hat = inv(R_hat)

A_true = np.eye(d) - B_true
# print("A_true = \n",A_true)
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 1)


print("likelihood_true = ", likelihood_true)
print("G_true = \n", G_true)
print("G_est = \n", best_G)
print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
# print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
print("Final Loss = ", best_loss)
print("Final penalty = ", best_penalty)
print("Final likelihood = ", best_likelihood)
print("seed = ", best_seed)
print("")


random seed =  7
likelihood_true =  4.01259352685402
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
G_est = 
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
P = 
 [[-0.00 1.00 -0.00 -0.01]
 [1.00 -1.00 -0.01 -0.00]
 [-0.00 0.00 -0.87 0.47]
 [33.13 0.00 -2.10 0.00]]
U = 
 [[13.82 404.74 -5.62 13.82]
 [13.82 -31.67 -5.46 -5.81]
 [-5.81 357670.38 22.13 13.82]
 [-1148800.70 8917.21 702638.54 2.81]]
Final Loss =  7.51226263437615
Final penalty =  3.5000000000012768
Final likelihood =  4.012262634374872
seed =  0



In [4]:
# clamp
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

seed = 7
n, d = 10000, 4
graph_type, degree = 'ER', 1    # ER1 graph
B_scale = 1.0
noise_type = 'gaussian_ev'
print("random seed = ", seed)

Dataset = SyntheticDataset(n, d, graph_type, degree,
                        noise_type, B_scale, seed=seed)
data = Dataset.X
B_true = Dataset.B
G_true = Dataset.B_bin

R_hat = np.cov(data.T)
d = R_hat.shape[0]
Omega_true = np.eye(d)
Theta_hat = inv(R_hat)

A_true = np.eye(d) - B_true
# print("A_true = \n",A_true)
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_clamp(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 1)


print("likelihood_true = ", likelihood_true)
print("G_true = \n", G_true)
print("G_est = \n", best_G)
print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
# print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
print("Final Loss = ", best_loss)
print("Final penalty = ", best_penalty)
print("Final likelihood = ", best_likelihood)
print("seed = ", best_seed)
print("")


random seed =  7
likelihood_true =  4.01259352685402
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
G_est = 
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
P = 
 [[-0.00 1.00 -0.00 -0.01]
 [1.00 -1.00 -0.01 -0.00]
 [-0.00 0.00 -0.87 0.47]
 [33.13 0.00 -2.10 0.00]]
U = 
 [[10.00 10.00 -5.62 10.00]
 [10.00 -10.00 -5.46 -5.81]
 [-5.81 9.97 10.00 9.99]
 [-10.00 9.91 10.00 2.81]]
Final Loss =  7.51226263437615
Final penalty =  3.5000000000012768
Final likelihood =  4.012262634374872
seed =  0



In [5]:
# reg
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

seed = 7
n, d = 10000, 4
graph_type, degree = 'ER', 1    # ER1 graph
B_scale = 1.0
noise_type = 'gaussian_ev'
print("random seed = ", seed)

Dataset = SyntheticDataset(n, d, graph_type, degree,
                        noise_type, B_scale, seed=seed)
data = Dataset.X
B_true = Dataset.B
G_true = Dataset.B_bin

R_hat = np.cov(data.T)
d = R_hat.shape[0]
Omega_true = np.eye(d)
Theta_hat = inv(R_hat)

A_true = np.eye(d) - B_true
# print("A_true = \n",A_true)
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss_reg(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 1)


print("likelihood_true = ", likelihood_true)
print("G_true = \n", G_true)
print("G_est = \n", best_G)
print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
# print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
print("Final Loss = ", best_loss)
print("Final penalty = ", best_penalty)
print("Final likelihood = ", best_likelihood)
print("seed = ", best_seed)
print("")


random seed =  7
likelihood_true =  4.01259352685402
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-1.00 0.00 -0.03 1.00]
 [-1.00 -1.00 -3.41 85.10]
 [0.46 -0.00 0.47 -0.00]
 [1.01 -0.98 22.67 0.00]]
U = 
 [[-2049.02 88.83 -4.24 19814528.36]
 [-1260004.80 -41.74 -50.75 -22.28]
 [-2.75 1832.06 17293.11 4.90]
 [108579.89 -16.85 -74489.69 192187.87]]
Final Loss =  34.63766272285886
Final penalty =  2.5000005473840012
Final likelihood =  32.13766217547486
seed =  0



In [6]:
# reg reset
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

seed = 7
n, d = 10000, 4
graph_type, degree = 'ER', 1    # ER1 graph
B_scale = 1.0
noise_type = 'gaussian_ev'
print("random seed = ", seed)

Dataset = SyntheticDataset(n, d, graph_type, degree,
                        noise_type, B_scale, seed=seed)
data = Dataset.X
B_true = Dataset.B
G_true = Dataset.B_bin

R_hat = np.cov(data.T)
d = R_hat.shape[0]
Omega_true = np.eye(d)
Theta_hat = inv(R_hat)

A_true = np.eye(d) - B_true
# print("A_true = \n",A_true)
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss_reg_reset(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 1)


print("likelihood_true = ", likelihood_true)
print("G_true = \n", G_true)
print("G_est = \n", best_G)
print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
# print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
print("Final Loss = ", best_loss)
print("Final penalty = ", best_penalty)
print("Final likelihood = ", best_likelihood)
print("seed = ", best_seed)
print("")


random seed =  7
[Step 6] Corrected 1 entries (P small, U large)
[Step 16] Corrected 1 entries (P small, U large)
[Step 17] Corrected 1 entries (P small, U large)
[Step 27] Corrected 1 entries (P small, U large)
[Step 41] Corrected 1 entries (P small, U large)
[Step 48] Corrected 1 entries (P small, U large)
[Step 55] Corrected 1 entries (P small, U large)
[Step 61] Corrected 1 entries (P small, U large)
[Step 69] Corrected 1 entries (P small, U large)
[Step 270] Corrected 1 entries (P small, U large)
[Step 271] Corrected 1 entries (P small, U large)
[Step 282] Corrected 1 entries (P small, U large)
[Step 283] Corrected 1 entries (P small, U large)
[Step 2815] Corrected 1 entries (P small, U large)
[Step 2816] Corrected 1 entries (P small, U large)
[Step 2817] Corrected 1 entries (P small, U large)
[Step 2818] Corrected 1 entries (P small, U large)
[Step 2819] Corrected 1 entries (P small, U large)
[Step 2820] Corrected 1 entries (P small, U large)
[Step 2821] Corrected 1 entries (P sm

## Test Regularization on 10 Graph With 300-times Findbest-Likelihood

In [ ]:
# No regularization

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-0.00 0.01 -0.00 1.01]
 [-0.02 1.01 -0.01 0.01]
 [-0.01 -0.01 1.00 -1.98]
 [0.99 0.11 -0.01 -0.88]]
U = 
 [[0.90 -5.39 -5.60 557.58]
 [-5.54 210431.85 -5.71 -5.79]
 [-5.69 -5.60 13.82 -1839.69]
 [13.82 -27.46 -5.91 -130344.91]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[1.70 1.65 1.79 0.00]
 [0.96 -0.79 -0.00 -0.61]
 [-0.01 0.26 1.00 0.00]
 [1.00 0.49 -0.60 -2.85]]
U = 
 [[6.85 13.82 6.89 -5.71]
 [6.80 17.20 -5.68 46589.04]
 [-5.88 -16.81 12231.42 -5.85]
 [13

In [ ]:
# clamp
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_fb_l_clamp(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0


likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-0.00 0.01 -0.00 1.01]
 [-0.02 1.01 -0.01 0.01]
 [-0.01 -0.01 1.00 -1.27]
 [0.99 0.11 -0.01 -0.88]]
U = 
 [[0.90 -5.39 -5.60 10.00]
 [-5.54 10.00 -5.71 -5.79]
 [-5.69 -5.60 10.00 -10.00]
 [10.00 -10.00 -5.91 -10.00]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 1. 0.]]
P = 
 [[1.77 0.04 0.00 -2.36]
 [-2.19 1.38 -0.00 -0.00]
 [1.00 0.07 0.02 -0.04]
 [1.30 0.62 -0.31 -0.65]]
U = 
 [[9.05 -5.38 -5.63 10.00]
 [-9.40 10.00 -5.67 -8.87]
 [10.00 -10.00 10.00 -10.00]
 [-10.00 9.91 10.00 6.27]]
Final Loss =  6.006935853065316
Final penalty =  2.000000

In [ ]:
# reg
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_fb_l_reg(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[1.01 1.01 -0.00 -0.00]
 [0.01 -1.01 -0.01 -0.02]
 [-0.00 0.01 1.00 -0.01]
 [-0.00 0.02 -0.00 0.99]]
U = 
 [[156.16 -12031409.55 -4.09 -4.30]
 [4.96 29.93 -4.20 -4.23]
 [-4.07 -4.07 12435.53 4.83]
 [-4.17 -4.26 -4.08 1856.27]]
Final Loss =  4.971958647182529
Final penalty =  1.0000000044657082
Final likelihood =  3.97195864271682
seed =  245

random seed =  1
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[1.00 1.31 1.79 -1.70]
 [-5.38 -1.00 -0.00 -0.96]
 [-0.00 0.99 1.00 0.00]
 [0.38 0.49 2.41 -1.00]]
U = 
 [[17.40 5.88 6.03 4.70]
 [-11.76 26.77 -4.51 66880.25]
 [-4.19 -130.03 1741.75 -3.88]
 [-183119.21 -15965.41 -10.08 44.30]]
Final Loss =  5.

In [ ]:
# reg reset
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_fb_l_reg_reset(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[1.01 0.01 -0.00 -0.00]
 [0.01 1.01 -0.01 -0.02]
 [0.33 -0.79 1.00 0.13]
 [-0.00 -0.02 -0.01 0.99]]
U = 
 [[181.57 -2.82 -2.88 -2.75]
 [-2.66 19.79 -2.89 -2.66]
 [-1802064.78 -6.03 98.77 -4.46]
 [-2.66 -2.81 -2.69 5071.38]]
Final Loss =  3.9720425043004126
Final penalty =  5.109406682066151e-06
Final likelihood =  3.9720373948937304
seed =  223

random seed =  1
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]]
P = 
 [[1.00 0.05 -0.25 2.14]
 [-4.01 1.38 0.01 0.02]
 [0.27 -0.02 -0.80 -0.46]
 [1.18 0.62 0.41 0.72]]
U = 
 [[13.41 -2.82 -2.76 3.72]
 [-4.49 596.60 -2.89 -2.66]
 [-9729.71 -2.65 7.18 -108.32]
 [-8.54 4.59 38.81 186.49]]
Final Loss =  5.9601073489

## Test Regularization on 10 Graph With 300-times Findbest

In [11]:
# No regularization

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-0.00 0.01 -0.00 1.01]
 [-0.02 1.01 -0.01 0.01]
 [-0.01 -0.01 1.00 -1.98]
 [0.99 0.11 -0.01 -0.88]]
U = 
 [[0.90 -5.39 -5.60 557.58]
 [-5.54 210431.85 -5.71 -5.79]
 [-5.69 -5.60 13.82 -1839.69]
 [13.82 -27.46 -5.91 -130344.91]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
P = 
 [[1.00 -1.31 1.79 -0.23]
 [-0.00 1.00 -0.00 -1.10]
 [1.64 -1.02 1.00 0.43]
 [2.24 -13.14 -1.75 -0.82]]
U = 
 [[6553.63 5.56 13.82 -5.58]
 [-5.80 13.82 -5.68 7.05]
 [-890198.02 -269.51 1472.30 1578.30]
 [-16742.40 -53.58 -9.57 13.82]]
Final Loss

In [12]:
# clamp
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_clamp(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0


likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-0.00 0.01 -0.00 1.01]
 [-0.02 1.01 -0.01 0.01]
 [-0.01 -0.01 1.00 -1.27]
 [0.99 0.11 -0.01 -0.88]]
U = 
 [[0.90 -5.39 -5.60 10.00]
 [-5.54 10.00 -5.71 -5.79]
 [-5.69 -5.60 10.00 -10.00]
 [10.00 -10.00 -5.91 -10.00]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 1. 0.]]
P = 
 [[1.77 0.04 0.00 -2.36]
 [-2.19 1.38 -0.00 -0.00]
 [1.00 0.07 0.02 -0.04]
 [1.30 0.62 -0.31 -0.65]]
U = 
 [[9.05 -5.38 -5.63 10.00]
 [-9.40 10.00 -5.67 -8.87]
 [10.00 -10.00 10.00 -10.00]
 [-10.00 9.91 10.00 6.27]]
Final Loss =  6.006935853065316
Final penalty =  2.000000

In [13]:
# reg
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss_reg(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[1.01 1.01 -0.00 -0.00]
 [0.01 -1.01 -0.01 -0.02]
 [-0.00 0.01 1.00 -0.01]
 [-0.00 0.02 -0.00 0.99]]
U = 
 [[156.16 -12031409.55 -4.09 -4.30]
 [4.96 29.93 -4.20 -4.23]
 [-4.07 -4.07 12435.53 4.83]
 [-4.17 -4.26 -4.08 1856.27]]
Final Loss =  4.971958647182529
Final penalty =  1.0000000044657082
Final likelihood =  3.97195864271682
seed =  245

random seed =  1
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[1.00 1.31 1.79 -1.70]
 [-5.38 -1.00 -0.00 -0.96]
 [-0.00 0.99 1.00 0.00]
 [0.38 0.49 2.41 -1.00]]
U = 
 [[17.40 5.88 6.03 4.70]
 [-11.76 26.77 -4.51 66880.25]
 [-4.19 -130.03 1741.75 -3.88]
 [-183119.21 -15965.41 -10.08 44.30]]
Final Loss =  5.

In [1]:
# reg reset
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

for seed in range(10):
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss_reg_reset(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)


    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


ModuleNotFoundError: No module named 'synthetic_dataset'