In [1]:
import sys, os
import numpy as np
from numpy.linalg import LinAlgError, inv
from scipy.linalg import sqrtm

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
print(os.getcwd())

from nodag.nodag_gumbel_softmax import train_gumbel_sgd 
from nodag.nodag_gs_findbest import nodag_findbest_loss, nodag_findbest_likelihood_penalty, calculate_shd

c:\Users\super\DAG\nodag


In [ ]:
# for i in range(1, 6):
#     X, Y, Z, G_true, CPDAG = generate_scm_data(i, 10000)
#     A_true = (np.eye(3) - G_true)
#     data = np.array([X, Y, Z]).T
#     R_hat = np.cov(data.T)
#     B_init = np.random.randn(*R_hat.shape)
#     likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)
#     best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest(R_hat = R_hat, times = 100)
#     print("SCM: ",i)
#     print("likelihood_true = ", likelihood_true)
#     print("G_true = \n", G_true)
#     print("G_est = \n", best_G)
#     # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
#     print("Final Loss = ", best_loss)
#     print("Final penalty = ", best_penalty)
#     print("Final likelihood = ", best_likelihood)
#     print("seed = ", best_seed)
#     print("")
    
    

SCM:  1
likelihood_true =  3.037318063988293
G_true = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
G_est = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Final Loss =  3.0370697380252674
Final penalty =  1.955358835544745e-12
Final likelihood =  3.037069738023312
seed =  87

SCM:  2
likelihood_true =  3.0179642443567762
G_true = 
 [[0 1 0]
 [0 0 0]
 [0 0 0]]
G_est = 
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
Final Loss =  3.5174811335654548
Final penalty =  0.49999999996025857
Final likelihood =  3.0174811336051963
seed =  87

SCM:  3
likelihood_true =  3.017964244356776
G_true = 
 [[0 1 0]
 [0 0 0]
 [0 1 0]]
G_est = 
 [[0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
Final Loss =  4.017474717799517
Final penalty =  0.9999999999597986
Final likelihood =  3.0174747178397183
seed =  74

SCM:  4
likelihood_true =  3.017964244356773
G_true = 
 [[0 1 0]
 [0 0 1]
 [0 0 0]]
G_est = 
 [[0. 0. 0.]
 [1. 0. 1.]
 [0. 0. 0.]]
Final Loss =  4.017433666743141
Final penalty =  1.0000000000007825
Final likelihood =  3.0174336667423587
seed =

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, tau = 0.2, lam = 0.5

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

seed = 7
n, d = 10000, 4
graph_type, degree = 'ER', 1    # ER1 graph
B_scale = 1.0
noise_type = 'gaussian_ev'
print("random seed = ", seed)

Dataset = SyntheticDataset(n, d, graph_type, degree,
                        noise_type, B_scale, seed=seed)
data = Dataset.X
B_true = Dataset.B
G_true = Dataset.B_bin

R_hat = np.cov(data.T)
d = R_hat.shape[0]
Omega_true = np.eye(d)
Theta_hat = inv(R_hat)

A_true = np.eye(d) - B_true
# print("A_true = \n",A_true)
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
# shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


# print("shd = ",shd)
print("likelihood_true = ", likelihood_true)
print("G_true = \n", G_true)
print("G_est = \n", best_G)
print("P = \n",best_P)
print("U = \n",best_U)
# print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
print("Final Loss = ", best_loss)
print("Final penalty = ", best_penalty)
print("Final likelihood = ", best_likelihood)
print("seed = ", best_seed)
print("")


random seed =  7
t =  0
t =  100
t =  200
shd =  0
likelihood_true =  4.01259352685402
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
P = 
 [[ 1.00046113e+00 -1.15117290e-03 -2.34171756e-03 -1.77796906e-01]
 [-6.91066275e+00  1.00265186e+00  8.30119365e-03  4.90711235e-03]
 [ 3.25044185e-01  4.06210003e-02  9.92935238e-01  3.03785023e-01]
 [ 6.83631026e-03  4.88418713e-03  1.84854404e+00  9.97881158e-01]]
U = 
 [[ 8.19145430e+04 -5.43966542e+00 -5.66551154e+00 -7.12239618e+00]
 [-1.84695720e+01  1.88505550e+02  1.38155096e+01 -5.80178763e+00]
 [-4.31972714e+08 -6.42505265e+02  3.33596444e+04 -6.70913540e+02]
 [ 5.99154254e+10 -5.72073202e+00  1.38155096e+01  9.62416701e+01]]
Final Loss =  5.512191080996524
Final penalty =  1.5000000000013352
Final likelihood =  4.012191080995189
seed =  223



## Test Findbest-Loss

In [ ]:
# findbest-loss, seed = 0-9, times = 300
# d = 4, degree = 1

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B
times = 10
for t in range(times):

    seed = t
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    #best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
    #print("best_B:\n", best_B)
    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
seed 0
seed 1
seed 2
seed 3
seed 4
seed 5
seed 6
seed 7
seed 8
seed 9
seed 10
seed 11
seed 12
seed 13
seed 14
seed 15
seed 16
seed 17
seed 18
seed 19
seed 20
seed 21
seed 22
seed 23
seed 24
seed 25
seed 26
seed 27
seed 28
seed 29
seed 30
seed 31
seed 32
seed 33
seed 34
seed 35
seed 36
seed 37
seed 38
seed 39
seed 40
seed 41
seed 42
seed 43
seed 44
seed 45
seed 46
seed 47
seed 48
seed 49
seed 50
seed 51
seed 52
seed 53
seed 54
seed 55
seed 56
seed 57
seed 58
seed 59
seed 60
seed 61
seed 62
seed 63
seed 64
seed 65
seed 66
seed 67
seed 68
seed 69
seed 70
seed 71
seed 72
seed 73
seed 74
seed 75
seed 76
seed 77
seed 78
seed 79
seed 80
seed 81
seed 82
seed 83
seed 84
seed 85
seed 86
seed 87
seed 88
seed 89
seed 90
seed 91
seed 92
seed 93
seed 94
seed 95
seed 96
seed 97
seed 98
seed 99
seed 100
seed 101
seed 102
seed 103
seed 104
seed 105
seed 106
seed 107
seed 108
seed 109
seed 110
seed 111
seed 112
seed 113
seed 114
seed 115
seed 116
seed 117
seed 118
seed 119
seed 120
seed

In [ ]:
# d = 5, degree = 2

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B
times = 10
for t in range(times):

    seed = t
    n, d = 10000, 5
    graph_type, degree = 'ER', 2    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    #best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
    #print("best_B:\n", best_B)
    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_loss(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")


random seed =  0
seed 0
seed 1
seed 2
seed 3
seed 4
seed 5
seed 6
seed 7
seed 8
seed 9
seed 10
seed 11
seed 12
seed 13
seed 14
seed 15
seed 16
seed 17
seed 18
seed 19
seed 20
seed 21
seed 22
seed 23
seed 24
seed 25
seed 26
seed 27
seed 28
seed 29
seed 30
seed 31
seed 32
seed 33
seed 34
seed 35
seed 36
seed 37
seed 38
seed 39
seed 40
seed 41
seed 42
seed 43
seed 44
seed 45
seed 46
seed 47
seed 48
seed 49
seed 50
seed 51
seed 52
seed 53
seed 54
seed 55
seed 56
seed 57
seed 58
seed 59
seed 60
seed 61
seed 62
seed 63
seed 64
seed 65
seed 66
seed 67
seed 68
seed 69
seed 70
seed 71
seed 72
seed 73
seed 74
seed 75
seed 76
seed 77
seed 78
seed 79
seed 80
seed 81
seed 82
seed 83
seed 84
seed 85
seed 86
seed 87
seed 88
seed 89
seed 90
seed 91
seed 92
seed 93
seed 94
seed 95
seed 96
seed 97
seed 98
seed 99
seed 100
seed 101
seed 102
seed 103
seed 104
seed 105
seed 106
seed 107
seed 108
seed 109
seed 110
seed 111
seed 112
seed 113
seed 114
seed 115
seed 116
seed 117
seed 118
seed 119
seed 120
seed

## Test Findbest-Likelihood

In [7]:
# findbest-likelihood, seed = 0-9, times = 300
# d = 4, degree = 1
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B
times = 10
for t in range(times):

    seed = t
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    #best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
    #print("best_B:\n", best_B)
    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-0.00 0.01 -0.00 1.01]
 [-0.02 1.01 -0.01 0.01]
 [-0.01 -0.01 1.00 -1.98]
 [0.99 0.11 -0.01 -0.88]]
U = 
 [[0.90 -5.39 -5.60 557.58]
 [-5.54 210431.85 -5.71 -5.79]
 [-5.69 -5.60 13.82 -1839.69]
 [13.82 -27.46 -5.91 -130344.91]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[1.70 1.65 1.79 0.00]
 [0.96 -0.79 -0.00 -0.61]
 [-0.01 0.26 1.00 0.00]
 [1.00 0.49 -0.60 -2.85]]
U = 
 [[6.85 13.82 6.89 -5.71]
 [6.80 17.20 -5.68 46589.04]
 [-5.88 -16.81 12231.42 -5.85]
 [13

KeyboardInterrupt: 

In [ ]:
# d = 5, degree = 2
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B
times = 10
for t in range(times):

    seed = t
    n, d = 10000, 5
    graph_type, degree = 'ER', 2    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    #best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
    #print("best_B:\n", best_B)
    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")

## Test Findbest-DAG

In [2]:
# Findbest-Likelihood-DAG, seed = 0-9, times = 300
# d = 4, degree = 1
from nodag.nodag_gs_findbest import nodag_fb_l_dag
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B
times = 10
for t in range(times):

    seed = t
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    #best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
    #print("best_B:\n", best_B)
    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed, thr = nodag_fb_l_dag(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("Thresholding = ",thr)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Thresholding =  1.0000000000000007
P = 
 [[-0.00 0.01 -0.00 1.01]
 [-0.02 1.01 -0.01 0.01]
 [-0.01 -0.01 1.00 -1.98]
 [0.99 0.11 -0.01 -0.88]]
U = 
 [[0.90 -5.39 -5.60 557.58]
 [-5.54 210431.85 -5.71 -5.79]
 [-5.69 -5.60 13.82 -1839.69]
 [13.82 -27.46 -5.91 -130344.91]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0 1 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
Thresholding =  0.9700000000000006
P = 
 [[1.70 1.65 1.79 0.00]
 [0.96 -0.79 -0.00 -0.61]
 [-0.01 0.26 1.00 0.00]
 [1.00 0.49 -0.60 -2.85]]
U = 
 [[6.85 13.82 6.89 -5.71]
 [6.80 17.20 -5.68 46589.0

In [3]:
# d = 5, degree = 2
from nodag.nodag_gs_findbest import nodag_fb_l_dag
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B
times = 10
for t in range(times):

    seed = t
    n, d = 10000, 5
    graph_type, degree = 'ER', 2    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)

    #best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
    #print("best_B:\n", best_B)
    best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed, thr = nodag_fb_l_dag(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("Thresholding = ",thr)
    print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
    print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  5.0328463177010825
G_true = 
 [[0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
G_est = 
 [[0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]
Thresholding =  1.0000000000000007
P = 
 [[-0.99 1.46 0.87 -0.00 0.00]
 [-1.64 -5.86 1.00 0.00 -0.01]
 [-61.91 -1.00 -0.01 1.54 -0.00]
 [0.43 1.50 12.22 1.00 0.00]
 [0.00 -0.01 0.02 -0.00 -1.00]]
U = 
 [[13.82 6.45 48.15 13.82 -5.30]
 [-7.55 -9.55 111703.87 -5.60 -5.46]
 [-14.33 6912.31 287.36 -32.15 -5.62]
 [-9.69 13.82 -9.54 38935.48 -5.88]
 [-5.60 -5.46 -5.81 -5.49 13.82]]
Final Loss =  8.032242405770951
Final penalty =  3.000000000004706
Final likelihood =  5.032242405766246
seed =  265

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  5.007642262846884
G_true = 
 [[0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
G_est = 
 [[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 1]
 [0 0 0 0 0]
 [

ValueError: min() iterable argument is empty

In [5]:
from nodag.nodag_gs_findbest import nodag_fb_l_dag
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

seed = 2
n, d = 10000, 5
graph_type, degree = 'ER', 2    # ER1 graph
B_scale = 1.0
noise_type = 'gaussian_ev'
print("random seed = ", seed)

Dataset = SyntheticDataset(n, d, graph_type, degree,
                        noise_type, B_scale, seed=seed)
data = Dataset.X
B_true = Dataset.B
G_true = Dataset.B_bin

R_hat = np.cov(data.T)
d = R_hat.shape[0]
Omega_true = np.eye(d)
Theta_hat = inv(R_hat)

A_true = np.eye(d) - B_true
# print("A_true = \n",A_true)
likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)
print("likelihood_true = ", likelihood_true)
print("G_true = \n", G_true)

#best_G, best_B,info = train_gumbel_sgd(Rhat_np = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2)
#print("best_B:\n", best_B)
best_G, best_B,best_P,best_U, best_loss, best_likelihood, best_penalty, best_seed, thr = nodag_fb_l_dag(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 10, max_steps=100000)
#shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)


#print("shd = ",shd)

print("G_est = \n", best_G)
print("Thresholding = ",thr)
print("P = \n", np.array2string(best_P, formatter={'float_kind':lambda x: f"{x:.2f}"}))
print("U = \n", np.array2string(best_U, formatter={'float_kind':lambda x: f"{x:.2f}"}))

# print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
print("Final Loss = ", best_loss)
print("Final penalty = ", best_penalty)
print("Final likelihood = ", best_likelihood)
print("seed = ", best_seed)
print("")

random seed =  2
likelihood_true =  4.96899347480357
G_true = 
 [[0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0.]]
t =  0
NaN at step 0.0015700157001570015 loss = nan
Current B = [[        nan         nan         nan         nan         nan]
 [        nan         nan         nan         nan         nan]
 [        nan         nan         nan         nan         nan]
 [        nan         nan         nan         nan         nan]
 [ 1.88696948  0.         -0.         -1.23150274 -1.02849234]]
NaN at step 0.05594055940559406 loss = nan
Current B = [[-6.18834243e-001 -0.00000000e+000  1.23583051e+000  0.00000000e+000
  -3.26472538e-001]
 [-0.00000000e+000  1.20166154e+000 -0.00000000e+000 -0.00000000e+000
  -0.00000000e+000]
 [-0.00000000e+000  2.79706282e-001  5.67942319e-001 -1.05894832e+153
   2.36572053e-001]
 [ 0.00000000e+000 -0.00000000e+000  0.00000000e+000              nan
   0.00000000e+000]
 [ 0.00000000e+000 -1.32036407e+000  0.00000000e+0

ValueError: min() iterable argument is empty