In [1]:
import sys, os
import numpy as np
from numpy.linalg import LinAlgError, inv
from scipy.linalg import sqrtm

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
print(os.getcwd())

c:\Users\super\DAG\nodag


In [2]:
from nodag.nodag_gs_findbest import nodag_findbest_loss, nodag_findbest_likelihood_penalty, calculate_shd

In [4]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, tau = 0.2, lam = 0.5

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    shd_sum += shd

    print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
shd =  1
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[-1.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  0.  0. -1.]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
t =  0
t =  100
t =  200
shd =  0
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[ 0.  1.  1.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 1.  0.  0. -1.]]
Final Loss =  6.497046976915103
Final penalty =  2.500000000000619
Final likelihood =  3.997046976914484
seed =  46

random seed =  2
t =  0
t =  100
t =  200
shd =  0
likelihood_true =  4.014033534766731
G_true = 
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Final Loss =  5.51302787550704
Final p

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.5, tau = 0.8

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5,tau_start = 0.8,tau_end = 0.8 , times = 300)
    shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    shd_sum += shd

    print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
shd =  0
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Final Loss =  4.972448795685077
Final penalty =  1.0007193796915714
Final likelihood =  3.9717294159935053
seed =  68

random seed =  1
t =  0
t =  100
t =  200
shd =  0
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[ 0.  1.  1.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0. -1.  0.]
 [ 0.  0.  0.  0.]]
Final Loss =  6.49410936371979
Final penalty =  2.4965561849723157
Final likelihood =  3.997553178747475
seed =  53

random seed =  2
t =  0
t =  100
t =  200
shd =  1
likelihood_true =  4.014033534766731
G_true = 
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]]
G_est = 
 [[ 0.  1.  0.  0.]
 [ 1. -1.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  0.  0.]]
Final Loss =  6.013899277913744
Final

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.5, tau = 0.2 -> 0.8
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5,tau_start = 0.2,tau_end = 0.8, times = 300)
    shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    shd_sum += shd

    print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
print("\n Average shd = ", shd_sum / times)

In [ ]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.5, tau = 0.8 -> 0.2
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5,tau_start = 0.8,tau_end = 0.2, times = 300)
    shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    shd_sum += shd

    print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
print("\n Average shd = ", shd_sum / times)