In [1]:
import sys, os
import numpy as np
from numpy.linalg import LinAlgError, inv
from scipy.linalg import sqrtm

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(r"C:\Users\super\DAG")
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
print(os.getcwd())

c:\Users\super\DAG\nodag


In [2]:
from nodag.nodag_gs_findbest import nodag_findbest_loss, nodag_findbest_likelihood_penalty, calculate_shd

In [4]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, tau = 0.2, lam = 0.5

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-1.76761996e-03  7.08558561e-03 -2.38728426e-03  1.01300509e+00]
 [-1.76357504e-02  1.00721349e+00 -7.46979368e-03  6.91349852e-03]
 [-5.61868363e-03 -7.44060211e-03  1.00260570e+00 -1.98278306e+00]
 [ 9.91304165e-01  1.14895610e-01 -5.55960132e-03 -8.78352890e-01]]
U = 
 [[ 9.03549819e-01 -5.39006928e+00 -5.60195870e+00  5.57584259e+02]
 [-5.54444778e+00  2.10431850e+05 -5.71410280e+00 -5.78638973e+00]
 [-5.69320410e+00 -5.59897728e+00  1.38155096e+01 -1.83968943e+03]
 [ 1.38155096e+01 -2.74637953e+01 -5.90944210e+00 -1.30344911e+05]]
Final Loss =  4.972038338746174
Final penalty =  1.000000000002756
Final likelihood =  3.972038338743418
seed =  202

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [0

In [5]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, tau = 0.2, lam = 0.8

from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.8, tau_end=0.8, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[-1.01300559e+00  7.28469555e-03 -2.38725778e-03  1.58442397e+01]
 [ 8.22233879e-01  1.00736773e+00  4.04558974e-01  4.61542038e-01]
 [ 3.50331675e-02 -7.34331798e-03  1.00260848e+00 -5.62325858e-03]
 [ 4.27998974e+01 -1.73489871e-02 -5.52207393e-03  9.91302599e-01]]
U = 
 [[ 5.56328114e+05 -6.38730531e+00  1.38152280e+01 -2.05521165e+01]
 [-5.56148248e+06  9.16906262e+03 -2.92731534e+03 -1.57680824e+07]
 [-1.33428849e+02 -6.38023268e+00  4.06395832e+02 -6.19065359e+00]
 [-1.77224599e+05  1.38145073e+01 -6.44060463e+00  1.93793193e+04]]
Final Loss =  4.972448795685077
Final penalty =  1.0007193796915714
Final likelihood =  3.9717294159935053
seed =  68

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [

In [6]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.5, tau = 0.2 -> 0.8
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.2, tau_end=0.8, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
P = 
 [[-1.76761996e-03  6.87825661e-03 -2.38734889e-03  1.01300509e+00]
 [-1.76355508e-02  1.00721349e+00 -7.46856561e-03  6.91362767e-03]
 [-5.61978403e-03 -7.44059582e-03  1.00260570e+00 -1.98278306e+00]
 [ 9.91304165e-01  1.14895610e-01 -5.55961046e-03 -8.78352890e-01]]
U = 
 [[ 9.04005496e-01 -5.92868934e+00 -5.91704578e+00  6.08943653e+02]
 [-5.93751009e+00  2.09415325e+05 -6.16708420e+00 -6.07726013e+00]
 [-6.00773690e+00 -5.98078561e+00  1.38155096e+01 -1.88988698e+03]
 [ 1.38154757e+01 -2.87675678e+01 -6.11652288e+00 -1.29864195e+05]]
Final Loss =  4.9742164431788805
Final penalty =  1.0021785805601926
Final likelihood =  3.9720378626186883
seed =  202

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]


In [7]:
# Find best penalty in best likelihoods, seed0-9
# d = 4, lam = 0.5, tau = 0.8 -> 0.2
from torch.utils.data import Dataset

from synthetic_dataset import SyntheticDataset
from synthetic_dataset import dataset_based_on_B

shd_sum = 0
times = 10

for seed in range(times):
    # Load dataset
    n, d = 10000, 4
    graph_type, degree = 'ER', 1    # ER1 graph
    B_scale = 1.0
    noise_type = 'gaussian_ev'
    print("random seed = ", seed)

    Dataset = SyntheticDataset(n, d, graph_type, degree,
                            noise_type, B_scale, seed=seed)
    data = Dataset.X
    B_true = Dataset.B
    G_true = Dataset.B_bin

    R_hat = np.cov(data.T)
    d = R_hat.shape[0]
    Omega_true = np.eye(d)
    Theta_hat = inv(R_hat)

    A_true = np.eye(d) - B_true
    # print("A_true = \n",A_true)
    likelihood_true = - 2 * np.log(np.linalg.det(A_true)) + np.trace(A_true.T @ R_hat @ A_true)


    best_G, best_B, best_P, best_U, best_loss, best_likelihood, best_penalty, best_seed = nodag_findbest_likelihood_penalty(R_hat = R_hat,lam = 0.5, tau_start=0.8, tau_end=0.2, times = 300)
    #shd, est_cpdag, true_cpdag = calculate_shd(best_G, G_true)
    #shd_sum += shd

    #print("shd = ",shd)
    print("likelihood_true = ", likelihood_true)
    print("G_true = \n", G_true)
    print("G_est = \n", best_G)
    print("P = \n", best_P)
    print("U = \n", best_U)
    # print("Is in MEC: ", MEC.is_in_markov_equiv_class(G_true, best_B))
    print("Final Loss = ", best_loss)
    print("Final penalty = ", best_penalty)
    print("Final likelihood = ", best_likelihood)
    print("seed = ", best_seed)
    print("")
#print("\n Average shd = ", shd_sum / times)

random seed =  0
t =  0
t =  100
t =  200
likelihood_true =  3.9726462866418357
G_true = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
G_est = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P = 
 [[-1.01300559e+00  7.28473447e-03 -2.38726650e-03  1.58442397e+01]
 [ 8.22233879e-01  1.00736773e+00  4.04558974e-01  4.61542038e-01]
 [ 3.50331675e-02 -7.34332391e-03  1.00260848e+00 -5.62329015e-03]
 [ 4.27998974e+01 -1.73489871e-02 -5.54421030e-03  9.91302599e-01]]
U = 
 [[ 5.56832822e+05 -5.86213250e+00  1.38154981e+01 -2.06014474e+01]
 [-5.56086846e+06  9.16985929e+03 -2.92650989e+03 -1.57704440e+07]
 [-1.33273599e+02 -5.95532365e+00  4.05461471e+02 -5.62134841e+00]
 [-1.76917492e+05  1.38153188e+01 -6.00620781e+00  1.93229782e+04]]
Final Loss =  4.971729535391637
Final penalty =  1.0000000000005078
Final likelihood =  3.9717295353911286
seed =  68

random seed =  1
t =  0
t =  100
t =  200
likelihood_true =  3.9974760872380175
G_true = 
 [[0. 1. 1. 1.]
 [